# Generated by Django 3.0.6 on 2021-02-19 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=60)),
                ('Categoria', models.CharField(choices=[('CiberSeguridad', 'Ciberseguridad'), ('Inteligencia de Seguridad', 'Seginteligencia'), ('SIEM', 'Siem'), ('Cloud', 'Cloud'), ('IOT', 'Iot'), ('Gestión de Vulnerabilidades', 'Gesvulnerabilidad')], max_length=40)),
                ('MiniDes', models.CharField(max_length=140)),
                ('Miniatura', models.ImageField(upload_to='imagenes/%A/%m/%d/')),
                ('Fecha', models.CharField(max_length=8)),
                ('Destacados', models.BooleanField(default=False)),
                ('Contenido', models.TextField()),
                ('FechaCreacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Slug', models.SlugField()),
            ],
        ),
    ]
